pipeline{

    agent any

    environment{
        IMAGE_NAME = "manojkrishnappa/rag-image:${GIT_COMMIT}"
    }
    stages{
        stage('GITCHECKOUT'){
            steps{
                git url: 'https://github.com/ManojKRISHNAPPA/quantam-vector-batch-109.git',
                branch: 'production'
            }
        }
        stage('DOCKERBUILD'){
            steps{
                sh '''
                    printenv
                    cd code/
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }
        stage('CONTAINERTEST'){
            steps{
                sh '''
                    docker run -it -d --name c1 -p 8501:8501 ${IMAGE_NAME}
                '''
            }
        }
    }
}