pipeline{

    agent any

    environment{
        IMAGE_NAME = "manojkrishnappa/rag-image:${GIT_COMMIT}"
    }
    stages{
        stage('GITCHECKOUT'){
            steps{
                git url: 'https://github.com/ManojKRISHNAPPA/quantam-vector-batch-109.git',
                branch: 'production'
            }
        }
        stage('DOCKERBUILD'){
            steps{
                sh '''
                    printenv
                    cd code/
                    docker build -t ${IMAGE_NAME} .
                '''
            }
        }
        stage('CONTAINERTEST'){
            steps{
                sh '''
                    docker kill c1
                    docker rm c1
                    docker run -it -d --name c1 -p 8501:8501 ${IMAGE_NAME}
                '''
            }
        }
        stage('LOGIN TO DOCKER HUB'){
            steps{
                withCredentials([usernamePassword(credentialsId: 'docker-creds', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh '''
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    '''
                }
            }
        }
        stage('DOCKER PUSH'){
            steps{
                sh '''
                    docker push ${IMAGE_NAME}
                '''
            }
        }
    }
}